# Generated by Django 3.0.7 on 2020-06-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='save_info',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipping_address',
        ),
    ]
