# Generated by Django 3.0.7 on 2020-06-04 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20200604_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckOut',
            new_name='BillingAddress',
        ),
    ]
